### ISSUE TITLE
Error reading .ico files

### ISSUE THREAD

**Issue by Loilo** [egy186/icojs#7]
I'm trying to extract images of some Windows icons (from the infamous `shell32.dll`), running on latest stable Node.js (7.2.1).

Sadly this doesn't work. From the about 2000 icons

* <del>≈1500 generate an `ArrayBuffer` (and thus a file) of 20 bytes</del>
  solved, see comment below
* ≈500 are failing completely with the following error:

```
TypeError: Cannot read property '2' of undefined
    at Object.from4bit (/path/to/project/node_modules/icojs/src/image-data.js:48:28)
    at Promise.all.range.map.i (/path/to/project/node_modules/icojs/src/ico.js:45:36)
    at Array.map (native)
    at Object.parse (/path/to/project/node_modules/icojs/src/ico.js:34:64)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

No idea where exactly that's coming from. [Attaching](https://github.com/egy186/icojs/files/670168/icons.zip) one `.ico` file for each case.

**Comment by Loilo** [comment]
I'll need to revalidate my case, the 20 bytes buffer error must be on my side (since it works on the icojs demo page).

The other case with the failing icons should still be valid though. Seems to have to do with 8bit depth.

**Comment by egy186** [comment]
Confirmed NOT working when `biClrUsed` of the [BITMAPINFOHEADER](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183376(v=vs.85).aspx) is `0`. I'll fix it.
